import { IPlayer } from '../components/pages/Players/Players'

export const playersList: IPlayer[] = [
	// список игроков для первичной загрузки (либо если прописать localStorage.clear())
	{
		photo: '/photos/jaylen-adams.png',
		name: 'Jaylen Adams',
		position: 'Defender',
		team: 'Portland trail blazers',
		height_cm: '183',
		weight_kg: '84',
		birthday: '01/01/1996',
		number: '10',
	},
	{
		photo: '/photos/kyle-anderson.png',
		name: 'Kyle Anderson',
		position: 'Guard Forward',
		team: 'Memphis Grizzlies',
		height_cm: '198',
		weight_kg: '90',
		birthday: '01/01/1993',
		number: '1',
	},
	{
		photo: '/photos/malik-beasley.png',
		name: 'Malik Beasley',
		position: 'Forward',
		team: 'Minnesota timberwolves',
		height_cm: '193',
		weight_kg: '92',
		birthday: '01/01/200',
		number: '5',
	},
	{
		photo: '/photos/troy-daniels.png',
		name: 'Troy Daniels',
		position: 'Defender',
		team: 'Denver Nuggets',
		height_cm: '193',
		weight_kg: '89',
		birthday: '01/01/1991',
		number: '30',
	},
	{
		photo: '/photos/danilo-gallinari.png',
		name: 'Danilo Gallinari',
		position: 'Center Forward',
		team: 'Oklahoma city thunder',
		height_cm: '208',
		weight_kg: '93',
		birthday: '01/01/1988',
		number: '8',
	},
	{
		photo: '/photos/al-horford.png',
		name: 'Al Horford',
		position: 'Guard Forward',
		team: 'Philadelphia 76ers',
		height_cm: '206',
		weight_kg: '92',
		birthday: '01/01/1986',
		number: '42',
	},
	{
		photo: '/photos/bolbol.png',
		name: 'Bol Bol',
		position: 'Center Forward',
		team: 'Denver Nuggets',
		height_cm: '218',
		weight_kg: '100',
		birthday: '01/01/2003',
		number: '10',
	},
	{
		photo: '/photos/r.j.-hampton-1630181.png',
		name: 'R. J. Hampton',
		position: 'Defender',
		team: 'Denver Nuggets',
		height_cm: '193',
		weight_kg: '79',
		birthday: '01/01/2005',
		number: '',
	},
	{
		photo: '/photos/vlatko-cancar.png',
		name: 'Vlatko Cancar',
		position: 'Forward',
		team: 'Denver Nuggets',
		height_cm: '203',
		weight_kg: '107',
		birthday: '01/01/2001',
		number: '31',
	},
	{
		photo: '/photos/greg-whittington.png',
		name: 'Greg Whittington',
		position: 'Forward',
		team: 'Denver Nuggets',
		height_cm: '206',
		weight_kg: '95',
		birthday: '01/01/1997',
		number: '22',
	},
	{
		photo: '/photos/gary-harris.png',
		name: 'Gary Harris',
		position: 'Defender',
		team: 'Denver Nuggets',
		height_cm: '193',
		weight_kg: '95',
		birthday: '01/01/1998',
		number: '14',
	},
	{
		photo: '/photos/jamal-murray.png',
		name: 'Jamal Murray',
		position: 'Defender',
		team: 'Denver Nuggets',
		height_cm: '193',
		weight_kg: '98',
		birthday: '01/01/2001',
		number: '27',
	},
	{
		photo: '/photos/zeke.png',
		name: 'Zeke Nnaji',
		position: 'Forward-Center',
		team: 'Denver Nuggets',
		height_cm: '211',
		weight_kg: '109',
		birthday: '01/01/2005',
		number: '',
	},
]
